import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dayitava Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="relative mx-auto flex flex-col content-start items-center justify-center min-h-screen">
        <h1 className="font-black text-white text-5xl">
          दायि<span className="italic font-medium text-purple-600">त्व</span>
        </h1>
      </main>
    </>
  );
}
